### ISSUE TITLE
issues with metrics computation

### ISSUE THREAD

**Issue by deepakri201** [boahK/MRI_Classifier#2]
Hi, 

I am in the process of using your pre-trained model on my own data. I've managed to run inference, but have a few issues with computing the classification metrics: 

In line 142: `classification_report = classification_report(actuals, predictions, target_names=labels, digits=4, output_dict=True)
` I got the following error: 
`ValueError: Number of classes, 5, does not match size of target_names, 8. Try specifying the labels parameter`

This was because there were no predictions for 3 of the classes. 

I then modified the line to: `classification_report = classification_report(actuals, predictions, labels=[0, 1, 2, 3, 4, 5, 6, 7], target_names=labels, digits=4, output_dict=True)`. Now I can create the `classification_report`. 

However, now the  `roc_auc_score` is not defined for this case:
`ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.`

Perhaps a try/catch could be added for this case. 

Thank you!

Deepa

**Comment by boahK** [comment]
Thanks for your comments.
I've revised the code (test.py) based on your comments. I've added the argument 'labels' in 'classification_report' to compute classification metrics. Also, I've added try-except lines to compute the ROC AUC score.
